  mongo:
    image: mongo:4.4.13
    container_name: mongo
    hostname: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
     - docker_kafka
    # Mounting volume to save data on host machine
    volumes:
     - ../mongodb/data:/data/db
    environment:
      # @TODO: Move this to env variables / secrets
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    hostname: mongo_express
    restart: always
    depends_on:
     mongo:
       condition: service_healthy
    ports:
      - 8081:8081
    networks:
     - docker_kafka
    environment:
      # @TODO: Move this to env variables / secrets
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/